name: Test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
              
            - name: ls
              run: |
                chmod +x script.sh
                ./script.sh